### ISSUE TITLE
Labels and defs for table in expanded

### ISSUE THREAD

**Issue by DVRPCfreight** [dvrpc/pa-tip#35]
There needs to be definitions for the phases in the expanded view tables. 
Values in the table are not labeled as in thousands, unit is unclear

**Comment by mmolta** [comment]
We just got all the new PDF's which has an updated CodeAbbrev file & I will talk to Jesse about how to incorporate them. Previous TIP apps had the Phase/Fund cells link directly to it, which seems acceptable.

**Comment by mmolta** [comment]
*values labeled as ($000), not (/usr/bin/bash00)
