### ISSUE TITLE
Save state of navbar search and category filter

### ISSUE THREAD

**Issue by jstrangfeld** [dvrpc/pa-tip#39]
When navigating back from expanded project to main view, save the state of the search in the navbar and the filter in the category dropdown.

**Comment by DVRPCfreight** [comment]
Can you clarify this a bit? What were your steps to create this issue. I have been unable to break the state between expanded and main with a search (from navbar) and filter applied. Is the state of the map changing or the tiles?

**Comment by jstrangfeld** [comment]
You're right. It does work already. It was late and I thought the blank navbar search field was an issue.
