### ISSUE TITLE
Add County and Municipal Boundaries as map layers

### ISSUE THREAD

**Issue by crvanpollard** [dvrpc/pa-tip#45]
County and Municipal Boundaries (?) should be added to the map as map layers/overlays.
A standard basemap layer that we usually apply to most web mapping application to show users the extent of our projects (and region) and it allows County and Municipal planning partners to easy and quick view the projects in their areas.

Take a look at how I added the County Boundaries from @DVRPCfreight tile server in this project:
https://github.com/crvanpollard/greensolarenergy

**Comment by DVRPCfreight** [comment]
Could the Office of GIS provide some styles that match the Mapbox GL streets v9 style with the boundaries. You can do this from Maputnik and use this as a starting point `https://raw.githubusercontent.com/dvrpc/pa-tip/master/src/components/map/style.json`. 
The boundaries URL as a source is available here: 'https://a.michaelruane.com/data/dvrpc-municipal.json'.
