### ISSUE TITLE
Add TIP project linear features 

### ISSUE THREAD

**Issue by crvanpollard** [dvrpc/pa-tip#46]
Include TIP Projects Linear Features as a map layer along with markers. 
Several TIP projects extent for several miles and can be miss leading have a simple marker in a location that does not capture the full extent of the project  

If not possible with current DRAFT version of web mapping application, one solution could be to include a link for users to explore the GIS data sets in a simple AGO web map. 
<img width="1382" alt="screen shot 2018-05-02 at 11 12 00 am" src="https://user-images.githubusercontent.com/4401281/39531719-d56e3d20-4df9-11e8-8520-418c6a0ba95f.png">

**Comment by crvanpollard** [comment]
@rbeatty1 @jstrangfeld @mmolta @DVRPCfreight 
I like the idea that we talked about yesterday. Changing the Project Icons to circles. This will clean up the map and allow for the linear projects (about 208 projects) to be displayed as well. A viable option to explore. 
<img width="469" alt="screen shot 2018-09-22 at 9 34 42 am" src="https://user-images.githubusercontent.com/4401281/45917810-21946c80-be4b-11e8-93cf-207fc9622e0d.png">

**Comment by DVRPCfreight** [comment]
Linear features are now available as a part of the PA TIP vector tile dataset with layer name `patip_line`.
