### ISSUE TITLE
Google Streetview not unique for all projects

### ISSUE THREAD

**Issue by crvanpollard** [dvrpc/pa-tip#54]
Several projects ( MPMS 107544: Bridge Group N) have various locations throughout the region that are returning the same Google Streetview image for all locations. Clicking on a marker in Kennet Square, Chester County is showing a GSTV for a bridge located in New Hope, PA.
<img width="1179" alt="screen shot 2018-05-04 at 11 18 59 am" src="https://user-images.githubusercontent.com/4401281/39636063-1e35c9a8-4f8d-11e8-8881-cb623639eed1.png">

Also projects (some bike trail projects like 59434: Schuylkill River Trail (Q20)) do not have a Google Streetview image and should probably have a description indicating that "Streetview is not available"? Not sure how to check this but may be able to add a field to the GIS layers with a Yes or No value.

**Comment by jstrangfeld** [comment]
I'm going to split this into two issues. See #55 for when street view imagery is not available.

**Comment by jstrangfeld** [comment]
To solve the duplicate MPMS problem, we need to use the geometry from ArcGIS rather than the attributes. The geometry is unique to each feature, while the LAG and LNG attributes are shared between features based on the original data.
